### ISSUE TITLE
Code for analyzing snATAC-seq data

### ISSUE THREAD

**Issue by ttgump** [marzamKI/spatial_atac#1]
Hi,
1. Is there the code for integrating and annotating cluster labels of spatial ATAC-seq data and snATAC-seq data in mouse embryo displayed in Figure 1 h-j? 
2. Is it possible for you to provide the cluster label names such as "Forebrain", "Facial/bone" displayed in Figure 1 c-g? I know you have provided the code for unsupervised clustering, but how can I know what do cluster "0", "1", "2", ... mean?
Thanks.

**Comment by marzamKI** [comment]
Hi ttgump,

Thank you for reaching out and for your interest in our research and data!

1. I added a metadata file to this repo (metadata_integrated_snatac_ours.csv), which includes annotated cluster labels for the snATAC and sATAC integrated object (Figure 1 h-j). The naming was assigned by exploring the expression of the cluster markers from the integrated dataset in the MOCA reference atlas here [https://oncoscape.v3.sttrcancer.org/atlas.gs.washington.edu.mouse.rna/genes] with manual supervision based on the spatial location.
In addition, you can find the code used to integrate the datasets in the file named embryo_sc_integration.R (lines 1-225).

2. You can find the cluster IDs (0,1,2 etc) in the metadata published on GEO ([https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE214991]). The annotations are as follows:

```
combined <- RenameIdents(combined, 
"5" = "Forebrain", "7" = "Midbrain", "2" = "Hindbrain", 
"9" =  "Periventricular", "3" = "Meningeal/PNS", "4" = "Meningeal/PNS", "8" = "Internal", 
"0" = "Facial/bone", "1" = "Muscle/Heart", "10" = "Limb", "6" = "Liver")

```

Let me know if there's anything else I can do for you!
