### ISSUE TITLE
Fragment of snATAC in E12.5 is large smaller than other data

### ISSUE THREAD

**Issue by cynthier** [marzamKI/spatial_atac#3]
Hi, I notied that Fragment of snATAC is largely smaller than the data in  other time cource, could I know the reasons?

**Comment by marzamKI** [comment]
Dear cynthier,

Yes, It is indeed smaller. 
That's because we obtained fewer cells from that sample (153 for e12.5, vs 970 for e13.5 and 756 for e.15.5).

Cheers,
Margherita
