### ISSUE TITLE
 mouse embryos spatial-ATAC spots annotation

### ISSUE THREAD

**Issue by dannihong** [marzamKI/spatial_atac#4]
Hi Margherita,

    Thanks for your great work and sharing the data and code.I am using your mouse embryos spatial-ATAC data in my project. I noticed that you have upload the tissue_tsv file in the github, while I want to know the cell type annotation or tissue type annotation in each spot in your paper, can you share me the metadata files for each mouse embryos samples? Thanks!

All the best,
Danni

**Comment by marzamKI** [comment]
Hey Danni,

You can find the medatata to the embryo object on GEO at [https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE214986](url)
Thank you for bringing this up: I will update the repo and include the link to the GEO submission so that it's easier to find for everyone! :)

M
