### ISSUE TITLE
Ask for cell type annotation marker list

### ISSUE THREAD

**Issue by dannihong** [marzamKI/spatial_atac#6]
Hi,

Sorry for troubling you. Can you share me the marker you used to perform the cell type annotation of the mouse embryos, and can you tell me how you annotate the cell type . Thanks a lot.

All the best

**Comment by marzamKI** [comment]
Hey,

We performed gene activity scoring and ran FindAllMarkers to get the top enriched genes. Then we looked at them at this link: https://oncoscape.v3.sttrcancer.org/atlas.gs.washington.edu.mouse.rna/genes and took the most recurrent cell type for annotation.
Hope this helps!

Cheers,
Margherita
