### ISSUE TITLE
The cell type annotation of snATAC-seq is incomplete compared to the manuscript 

### ISSUE THREAD

**Issue by Bink98** [marzamKI/spatial_atac#7]
Hi, 
I noticed that the cell type in [metadata_integrated_snatac_ours.csv](https://github.com/marzamKI/spatial_atac/blob/main/meta/metadata_integrated_snatac_ours.csv) seems to be incomplete compared to the Fig.1j in the manuscript. Could you provide a complete file? Thanks.

**Comment by marzamKI** [comment]
Hi Bink98,

You can find the cluster annotations from Fig 1J under 'annotated_integrated_cl' in that metadata file. 

Cheers,
M
